export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE =  'LOGIN_USER_FAILURE';
export const LOGOUT_USER =  'LOGOUT_USER';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE';

export const FETCH_SINGLE_USERS_SUCCESS = 'FETCH_SINGLE_USERS_SUCCESS';
export const FETCH_SINGLE_USERS_FAILURE = 'FETCH_SINGLE_USERS_FAILURE';

// SKILST ACTIONS

export const FETCH_SKILL_SUCCESS = 'FETCH_SKILL_SUCCESS';
export const FETCH_SKILL_REQUEST = 'FETCH_SKILL_REQUEST';
export const FETCH_SKILL_ERROR = 'FETCH_SKILL_ERROR';

export const FETCH_SKILL_CATEGORY_SUCCESS = 'FETCH_SKILL_CATEGORY_SUCCESS';
export const FETCH_SKILL_CATEGORY_REQUEST = 'FETCH_SKILL_CATEGORY_REQUEST';
export const FETCH_SKILL_CATEGORY_ERROR = 'FETCH_SKILL_CATEGORY_ERROR';

export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS';
export const FETCH_COMPANIES_ERROR = 'FETCH_COMPANIES_ERROR';


